# Generated by Django 2.1 on 2018-09-12 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('c_name', models.CharField(db_index=True, max_length=64, verbose_name='课程名称')),
                ('c_create_time', models.DurationField(verbose_name='创建时间')),
                ('c_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='课程介绍')),
                ('c_count', models.IntegerField(verbose_name='课程总数')),
                ('c_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('d_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('d_name', models.CharField(db_index=True, max_length=64, verbose_name='节课程名称')),
                ('d_number', models.IntegerField(verbose_name='课程第几章')),
                ('d_time_length', models.IntegerField(verbose_name='课程时长')),
                ('d_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('d_create_time', models.DurationField(blank=True, null=True, verbose_name='该科提出创造时间')),
                ('d_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('d_cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Course')),
            ],
            options={
                'verbose_name_plural': '每门课的详情表',
            },
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('e_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('e_ttos_evaluate', models.CharField(blank=True, max_length=255, null=True, verbose_name='老师对学生评价')),
                ('e_stot_evaluate', models.CharField(blank=True, max_length=255, null=True, verbose_name='学生对老师评价')),
                ('e_ttos_score', models.IntegerField(blank=True, null=True, verbose_name='老师对学生的打分')),
                ('e_stot_score', models.IntegerField(blank=True, null=True, verbose_name='学生对老师的打分')),
                ('e_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('e_create_time', models.DurationField(verbose_name='创建时间')),
                ('e_did', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Detail')),
            ],
            options={
                'verbose_name_plural': '评价表',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('g_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('g_record', models.CharField(max_length=12, verbose_name='状态')),
                ('g_time', models.DurationField(verbose_name='时间')),
                ('g_url', models.CharField(max_length=255, verbose_name='网址')),
                ('g_remark', models.CharField(max_length=255, verbose_name='备注')),
                ('g_did', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Detail')),
            ],
            options={
                'verbose_name_plural': '授课进度表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('s_account', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('s_password', models.CharField(max_length=32, verbose_name='密码')),
                ('s_name', models.CharField(db_index=True, max_length=32, verbose_name='姓名')),
                ('s_sex', models.BooleanField(verbose_name='性别')),
                ('s_state', models.BooleanField(verbose_name='状态')),
                ('s_create_time', models.DurationField(verbose_name='创建时间')),
                ('s_grade', models.CharField(blank=True, max_length=32, null=True, verbose_name='年级')),
                ('s_head_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像')),
                ('s_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('s_email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name_plural': '学生表',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('t_account', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('t_password', models.CharField(max_length=32, verbose_name='密码')),
                ('t_name', models.CharField(db_index=True, max_length=100, verbose_name='姓名')),
                ('t_age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('t_sex', models.BooleanField(verbose_name='性别')),
                ('t_state', models.BooleanField(verbose_name='状态')),
                ('t_create_time', models.DurationField(verbose_name='创建时间')),
                ('t_degree', models.CharField(blank=True, max_length=32, null=True, verbose_name='学位')),
                ('t_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='简介')),
                ('t_head_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像')),
                ('t_remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '老师表',
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='g_sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Student'),
        ),
        migrations.AddField(
            model_name='grant',
            name='g_tid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Teacher'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='e_sid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Student'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='e_tid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Teacher'),
        ),
    ]
